// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/gateway/v1/common.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChangeEvent represents a single data change event from the source.
type ChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of the change (CREATE, UPDATE, DELETE).
	Op string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	// The transaction/commit information from the source.
	Checkpoint *Checkpoint `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	// The primary key of the record.
	PrimaryKey string `protobuf:"bytes,3,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	// The data record after the change, in a standardized format (e.g., JSON string).
	Data          string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_api_gateway_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeEvent) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *ChangeEvent) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

func (x *ChangeEvent) GetPrimaryKey() string {
	if x != nil {
		return x.PrimaryKey
	}
	return ""
}

func (x *ChangeEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Checkpoint holds the information about the source's position.
type Checkpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For MySQL: binlog file name.
	MysqlBinlogFile string `protobuf:"bytes,1,opt,name=mysql_binlog_file,json=mysqlBinlogFile,proto3" json:"mysql_binlog_file,omitempty"`
	// For MySQL: binlog position.
	MysqlBinlogPos uint32 `protobuf:"varint,2,opt,name=mysql_binlog_pos,json=mysqlBinlogPos,proto3" json:"mysql_binlog_pos,omitempty"`
	// For PostgreSQL: Log Sequence Number (LSN).
	PostgresLsn string `protobuf:"bytes,3,opt,name=postgres_lsn,json=postgresLsn,proto3" json:"postgres_lsn,omitempty"`
	// For MongoDB: resume token.
	MongoResumeToken string `protobuf:"bytes,4,opt,name=mongo_resume_token,json=mongoResumeToken,proto3" json:"mongo_resume_token,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_api_gateway_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *Checkpoint) GetMysqlBinlogFile() string {
	if x != nil {
		return x.MysqlBinlogFile
	}
	return ""
}

func (x *Checkpoint) GetMysqlBinlogPos() uint32 {
	if x != nil {
		return x.MysqlBinlogPos
	}
	return 0
}

func (x *Checkpoint) GetPostgresLsn() string {
	if x != nil {
		return x.PostgresLsn
	}
	return ""
}

func (x *Checkpoint) GetMongoResumeToken() string {
	if x != nil {
		return x.MongoResumeToken
	}
	return ""
}

// SnapshotChunk represents a chunk of data from an initial snapshot.
type SnapshotChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The records in this chunk.
	Records []string `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// A cursor indicating the position in the snapshot.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// A hash for data validation (optional).
	ValidationHash string `protobuf:"bytes,3,opt,name=validation_hash,json=validationHash,proto3" json:"validation_hash,omitempty"`
	// For MySQL: binlog file name at the time of snapshot start.
	SnapshotBinlogFile string `protobuf:"bytes,4,opt,name=snapshot_binlog_file,json=snapshotBinlogFile,proto3" json:"snapshot_binlog_file,omitempty"`
	// For MySQL: binlog position at the time of snapshot start.
	SnapshotBinlogPos uint32 `protobuf:"varint,5,opt,name=snapshot_binlog_pos,json=snapshotBinlogPos,proto3" json:"snapshot_binlog_pos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotChunk) Reset() {
	*x = SnapshotChunk{}
	mi := &file_api_gateway_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunk) ProtoMessage() {}

func (x *SnapshotChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunk.ProtoReflect.Descriptor instead.
func (*SnapshotChunk) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *SnapshotChunk) GetRecords() []string {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SnapshotChunk) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SnapshotChunk) GetValidationHash() string {
	if x != nil {
		return x.ValidationHash
	}
	return ""
}

func (x *SnapshotChunk) GetSnapshotBinlogFile() string {
	if x != nil {
		return x.SnapshotBinlogFile
	}
	return ""
}

func (x *SnapshotChunk) GetSnapshotBinlogPos() uint32 {
	if x != nil {
		return x.SnapshotBinlogPos
	}
	return 0
}

var File_api_gateway_v1_common_proto protoreflect.FileDescriptor

const file_api_gateway_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/gateway/v1/common.proto\x12\n" +
	"gateway.v1\"\x8a\x01\n" +
	"\vChangeEvent\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x126\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x16.gateway.v1.CheckpointR\n" +
	"checkpoint\x12\x1f\n" +
	"\vprimary_key\x18\x03 \x01(\tR\n" +
	"primaryKey\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\xb3\x01\n" +
	"\n" +
	"Checkpoint\x12*\n" +
	"\x11mysql_binlog_file\x18\x01 \x01(\tR\x0fmysqlBinlogFile\x12(\n" +
	"\x10mysql_binlog_pos\x18\x02 \x01(\rR\x0emysqlBinlogPos\x12!\n" +
	"\fpostgres_lsn\x18\x03 \x01(\tR\vpostgresLsn\x12,\n" +
	"\x12mongo_resume_token\x18\x04 \x01(\tR\x10mongoResumeToken\"\xcc\x01\n" +
	"\rSnapshotChunk\x12\x18\n" +
	"\arecords\x18\x01 \x03(\tR\arecords\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12'\n" +
	"\x0fvalidation_hash\x18\x03 \x01(\tR\x0evalidationHash\x120\n" +
	"\x14snapshot_binlog_file\x18\x04 \x01(\tR\x12snapshotBinlogFile\x12.\n" +
	"\x13snapshot_binlog_pos\x18\x05 \x01(\rR\x11snapshotBinlogPosB<Z:github.com/yogoosoft/elasticrelay/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_common_proto_rawDescOnce sync.Once
	file_api_gateway_v1_common_proto_rawDescData []byte
)

func file_api_gateway_v1_common_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_common_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_common_proto_rawDesc), len(file_api_gateway_v1_common_proto_rawDesc)))
	})
	return file_api_gateway_v1_common_proto_rawDescData
}

var file_api_gateway_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_v1_common_proto_goTypes = []any{
	(*ChangeEvent)(nil),   // 0: gateway.v1.ChangeEvent
	(*Checkpoint)(nil),    // 1: gateway.v1.Checkpoint
	(*SnapshotChunk)(nil), // 2: gateway.v1.SnapshotChunk
}
var file_api_gateway_v1_common_proto_depIdxs = []int32{
	1, // 0: gateway.v1.ChangeEvent.checkpoint:type_name -> gateway.v1.Checkpoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_common_proto_init() }
func file_api_gateway_v1_common_proto_init() {
	if File_api_gateway_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_common_proto_rawDesc), len(file_api_gateway_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_gateway_v1_common_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_common_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_common_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_common_proto = out.File
	file_api_gateway_v1_common_proto_goTypes = nil
	file_api_gateway_v1_common_proto_depIdxs = nil
}
