// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/gateway/v1/config.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{0}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Configuration         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetConfigResponse) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Configuration         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateConfigRequest) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{4}
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *ReloadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbHost        string                 `protobuf:"bytes,1,opt,name=db_host,json=dbHost,proto3" json:"db_host,omitempty"`
	DbPort        int32                  `protobuf:"varint,2,opt,name=db_port,json=dbPort,proto3" json:"db_port,omitempty"`
	DbUser        string                 `protobuf:"bytes,3,opt,name=db_user,json=dbUser,proto3" json:"db_user,omitempty"`
	DbPassword    string                 `protobuf:"bytes,4,opt,name=db_password,json=dbPassword,proto3" json:"db_password,omitempty"`
	DbName        string                 `protobuf:"bytes,5,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	ServerId      uint32                 `protobuf:"varint,6,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	TableFilters  []string               `protobuf:"bytes,7,rep,name=table_filters,json=tableFilters,proto3" json:"table_filters,omitempty"`
	EsAddresses   []string               `protobuf:"bytes,8,rep,name=es_addresses,json=esAddresses,proto3" json:"es_addresses,omitempty"`
	EsUser        string                 `protobuf:"bytes,9,opt,name=es_user,json=esUser,proto3" json:"es_user,omitempty"`
	EsPassword    string                 `protobuf:"bytes,10,opt,name=es_password,json=esPassword,proto3" json:"es_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_gateway_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *Configuration) GetDbHost() string {
	if x != nil {
		return x.DbHost
	}
	return ""
}

func (x *Configuration) GetDbPort() int32 {
	if x != nil {
		return x.DbPort
	}
	return 0
}

func (x *Configuration) GetDbUser() string {
	if x != nil {
		return x.DbUser
	}
	return ""
}

func (x *Configuration) GetDbPassword() string {
	if x != nil {
		return x.DbPassword
	}
	return ""
}

func (x *Configuration) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *Configuration) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Configuration) GetTableFilters() []string {
	if x != nil {
		return x.TableFilters
	}
	return nil
}

func (x *Configuration) GetEsAddresses() []string {
	if x != nil {
		return x.EsAddresses
	}
	return nil
}

func (x *Configuration) GetEsUser() string {
	if x != nil {
		return x.EsUser
	}
	return ""
}

func (x *Configuration) GetEsPassword() string {
	if x != nil {
		return x.EsPassword
	}
	return ""
}

var File_api_gateway_v1_config_proto protoreflect.FileDescriptor

const file_api_gateway_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/gateway/v1/config.proto\x12\n" +
	"gateway.v1\"\x12\n" +
	"\x10GetConfigRequest\"F\n" +
	"\x11GetConfigResponse\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.gateway.v1.ConfigurationR\x06config\"H\n" +
	"\x13UpdateConfigRequest\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.gateway.v1.ConfigurationR\x06config\"J\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13ReloadConfigRequest\"J\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb3\x02\n" +
	"\rConfiguration\x12\x17\n" +
	"\adb_host\x18\x01 \x01(\tR\x06dbHost\x12\x17\n" +
	"\adb_port\x18\x02 \x01(\x05R\x06dbPort\x12\x17\n" +
	"\adb_user\x18\x03 \x01(\tR\x06dbUser\x12\x1f\n" +
	"\vdb_password\x18\x04 \x01(\tR\n" +
	"dbPassword\x12\x17\n" +
	"\adb_name\x18\x05 \x01(\tR\x06dbName\x12\x1b\n" +
	"\tserver_id\x18\x06 \x01(\rR\bserverId\x12#\n" +
	"\rtable_filters\x18\a \x03(\tR\ftableFilters\x12!\n" +
	"\fes_addresses\x18\b \x03(\tR\vesAddresses\x12\x17\n" +
	"\aes_user\x18\t \x01(\tR\x06esUser\x12\x1f\n" +
	"\ves_password\x18\n" +
	" \x01(\tR\n" +
	"esPassword2\xff\x01\n" +
	"\rConfigService\x12H\n" +
	"\tGetConfig\x12\x1c.gateway.v1.GetConfigRequest\x1a\x1d.gateway.v1.GetConfigResponse\x12Q\n" +
	"\fUpdateConfig\x12\x1f.gateway.v1.UpdateConfigRequest\x1a .gateway.v1.UpdateConfigResponse\x12Q\n" +
	"\fReloadConfig\x12\x1f.gateway.v1.ReloadConfigRequest\x1a .gateway.v1.ReloadConfigResponseB<Z:github.com/yogoosoft/elasticrelay/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_config_proto_rawDescOnce sync.Once
	file_api_gateway_v1_config_proto_rawDescData []byte
)

func file_api_gateway_v1_config_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_config_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_config_proto_rawDesc), len(file_api_gateway_v1_config_proto_rawDesc)))
	})
	return file_api_gateway_v1_config_proto_rawDescData
}

var file_api_gateway_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_gateway_v1_config_proto_goTypes = []any{
	(*GetConfigRequest)(nil),     // 0: gateway.v1.GetConfigRequest
	(*GetConfigResponse)(nil),    // 1: gateway.v1.GetConfigResponse
	(*UpdateConfigRequest)(nil),  // 2: gateway.v1.UpdateConfigRequest
	(*UpdateConfigResponse)(nil), // 3: gateway.v1.UpdateConfigResponse
	(*ReloadConfigRequest)(nil),  // 4: gateway.v1.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 5: gateway.v1.ReloadConfigResponse
	(*Configuration)(nil),        // 6: gateway.v1.Configuration
}
var file_api_gateway_v1_config_proto_depIdxs = []int32{
	6, // 0: gateway.v1.GetConfigResponse.config:type_name -> gateway.v1.Configuration
	6, // 1: gateway.v1.UpdateConfigRequest.config:type_name -> gateway.v1.Configuration
	0, // 2: gateway.v1.ConfigService.GetConfig:input_type -> gateway.v1.GetConfigRequest
	2, // 3: gateway.v1.ConfigService.UpdateConfig:input_type -> gateway.v1.UpdateConfigRequest
	4, // 4: gateway.v1.ConfigService.ReloadConfig:input_type -> gateway.v1.ReloadConfigRequest
	1, // 5: gateway.v1.ConfigService.GetConfig:output_type -> gateway.v1.GetConfigResponse
	3, // 6: gateway.v1.ConfigService.UpdateConfig:output_type -> gateway.v1.UpdateConfigResponse
	5, // 7: gateway.v1.ConfigService.ReloadConfig:output_type -> gateway.v1.ReloadConfigResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_config_proto_init() }
func file_api_gateway_v1_config_proto_init() {
	if File_api_gateway_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_config_proto_rawDesc), len(file_api_gateway_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_config_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_config_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_config_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_config_proto = out.File
	file_api_gateway_v1_config_proto_goTypes = nil
	file_api_gateway_v1_config_proto_depIdxs = nil
}
