// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/gateway/v1/connector.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorService_BeginSnapshot_FullMethodName    = "/gateway.v1.ConnectorService/BeginSnapshot"
	ConnectorService_StartCdc_FullMethodName         = "/gateway.v1.ConnectorService/StartCdc"
	ConnectorService_CommitCheckpoint_FullMethodName = "/gateway.v1.ConnectorService/CommitCheckpoint"
	ConnectorService_LoadCheckpoint_FullMethodName   = "/gateway.v1.ConnectorService/LoadCheckpoint"
)

// ConnectorServiceClient is the client API for ConnectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectorService is responsible for capturing data from source databases.
type ConnectorServiceClient interface {
	// Begins an initial consistent snapshot of a table.
	BeginSnapshot(ctx context.Context, in *BeginSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error)
	// Starts capturing Change Data Capture (CDC) events.
	StartCdc(ctx context.Context, in *StartCdcRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	// Commits a checkpoint, acknowledging that data up to this point has been processed.
	CommitCheckpoint(ctx context.Context, in *CommitCheckpointRequest, opts ...grpc.CallOption) (*CommitCheckpointResponse, error)
	// Loads an existing checkpoint for a job.
	LoadCheckpoint(ctx context.Context, in *LoadCheckpointRequest, opts ...grpc.CallOption) (*LoadCheckpointResponse, error)
}

type connectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorServiceClient(cc grpc.ClientConnInterface) ConnectorServiceClient {
	return &connectorServiceClient{cc}
}

func (c *connectorServiceClient) BeginSnapshot(ctx context.Context, in *BeginSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectorService_ServiceDesc.Streams[0], ConnectorService_BeginSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BeginSnapshotRequest, SnapshotChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorService_BeginSnapshotClient = grpc.ServerStreamingClient[SnapshotChunk]

func (c *connectorServiceClient) StartCdc(ctx context.Context, in *StartCdcRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectorService_ServiceDesc.Streams[1], ConnectorService_StartCdc_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartCdcRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorService_StartCdcClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *connectorServiceClient) CommitCheckpoint(ctx context.Context, in *CommitCheckpointRequest, opts ...grpc.CallOption) (*CommitCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitCheckpointResponse)
	err := c.cc.Invoke(ctx, ConnectorService_CommitCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorServiceClient) LoadCheckpoint(ctx context.Context, in *LoadCheckpointRequest, opts ...grpc.CallOption) (*LoadCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCheckpointResponse)
	err := c.cc.Invoke(ctx, ConnectorService_LoadCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConnectorServiceServer is the server API for ConnectorService service.
// All implementations must embed UnimplementedConnectorServiceServer
// for forward compatibility.
//
// ConnectorService is responsible for capturing data from source databases.
type ConnectorServiceServer interface {
	// Begins an initial consistent snapshot of a table.
	BeginSnapshot(*BeginSnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error
	// Starts capturing Change Data Capture (CDC) events.
	StartCdc(*StartCdcRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	// Commits a checkpoint, acknowledging that data up to this point has been processed.
	CommitCheckpoint(context.Context, *CommitCheckpointRequest) (*CommitCheckpointResponse, error)
	// Loads an existing checkpoint for a job.
	LoadCheckpoint(context.Context, *LoadCheckpointRequest) (*LoadCheckpointResponse, error)
	mustEmbedUnimplementedConnectorServiceServer()
}

// UnimplementedConnectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorServiceServer struct{}

func (UnimplementedConnectorServiceServer) BeginSnapshot(*BeginSnapshotRequest, grpc.ServerStreamingServer[SnapshotChunk]) error {
	return status.Errorf(codes.Unimplemented, "method BeginSnapshot not implemented")
}
func (UnimplementedConnectorServiceServer) StartCdc(*StartCdcRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StartCdc not implemented")
}
func (UnimplementedConnectorServiceServer) CommitCheckpoint(context.Context, *CommitCheckpointRequest) (*CommitCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitCheckpoint not implemented")
}
func (UnimplementedConnectorServiceServer) LoadCheckpoint(context.Context, *LoadCheckpointRequest) (*LoadCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadCheckpoint not implemented")
}
func (UnimplementedConnectorServiceServer) mustEmbedUnimplementedConnectorServiceServer() {}
func (UnimplementedConnectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeConnectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorServiceServer will
// result in compilation errors.
type UnsafeConnectorServiceServer interface {
	mustEmbedUnimplementedConnectorServiceServer()
}

func RegisterConnectorServiceServer(s grpc.ServiceRegistrar, srv ConnectorServiceServer) {
	// If the following call pancis, it indicates UnimplementedConnectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorService_ServiceDesc, srv)
}

func _ConnectorService_BeginSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BeginSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServiceServer).BeginSnapshot(m, &grpc.GenericServerStream[BeginSnapshotRequest, SnapshotChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorService_BeginSnapshotServer = grpc.ServerStreamingServer[SnapshotChunk]

func _ConnectorService_StartCdc_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartCdcRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConnectorServiceServer).StartCdc(m, &grpc.GenericServerStream[StartCdcRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorService_StartCdcServer = grpc.ServerStreamingServer[ChangeEvent]

func _ConnectorService_CommitCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).CommitCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_CommitCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).CommitCheckpoint(ctx, req.(*CommitCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorService_LoadCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorServiceServer).LoadCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorService_LoadCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorServiceServer).LoadCheckpoint(ctx, req.(*LoadCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConnectorService_ServiceDesc is the grpc.ServiceDesc for ConnectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.ConnectorService",
	HandlerType: (*ConnectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitCheckpoint",
			Handler:    _ConnectorService_CommitCheckpoint_Handler,
		},
		{
			MethodName: "LoadCheckpoint",
			Handler:    _ConnectorService_LoadCheckpoint_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BeginSnapshot",
			Handler:       _ConnectorService_BeginSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartCdc",
			Handler:       _ConnectorService_StartCdc_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/gateway/v1/connector.proto",
}
