// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/gateway/v1/connector.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeginSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginSnapshotRequest) Reset() {
	*x = BeginSnapshotRequest{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginSnapshotRequest) ProtoMessage() {}

func (x *BeginSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginSnapshotRequest.ProtoReflect.Descriptor instead.
func (*BeginSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{0}
}

func (x *BeginSnapshotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *BeginSnapshotRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type StartCdcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The checkpoint from which to start. If empty, starts from the latest position.
	StartCheckpoint *Checkpoint `protobuf:"bytes,2,opt,name=start_checkpoint,json=startCheckpoint,proto3" json:"start_checkpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartCdcRequest) Reset() {
	*x = StartCdcRequest{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCdcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCdcRequest) ProtoMessage() {}

func (x *StartCdcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCdcRequest.ProtoReflect.Descriptor instead.
func (*StartCdcRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{1}
}

func (x *StartCdcRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StartCdcRequest) GetStartCheckpoint() *Checkpoint {
	if x != nil {
		return x.StartCheckpoint
	}
	return nil
}

type CommitCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCheckpointRequest) Reset() {
	*x = CommitCheckpointRequest{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCheckpointRequest) ProtoMessage() {}

func (x *CommitCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCheckpointRequest.ProtoReflect.Descriptor instead.
func (*CommitCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{2}
}

func (x *CommitCheckpointRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CommitCheckpointRequest) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

type CommitCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCheckpointResponse) Reset() {
	*x = CommitCheckpointResponse{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCheckpointResponse) ProtoMessage() {}

func (x *CommitCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCheckpointResponse.ProtoReflect.Descriptor instead.
func (*CommitCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{3}
}

func (x *CommitCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LoadCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCheckpointRequest) Reset() {
	*x = LoadCheckpointRequest{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCheckpointRequest) ProtoMessage() {}

func (x *LoadCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCheckpointRequest.ProtoReflect.Descriptor instead.
func (*LoadCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{4}
}

func (x *LoadCheckpointRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type LoadCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Checkpoint    *Checkpoint            `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCheckpointResponse) Reset() {
	*x = LoadCheckpointResponse{}
	mi := &file_api_gateway_v1_connector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCheckpointResponse) ProtoMessage() {}

func (x *LoadCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_connector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCheckpointResponse.ProtoReflect.Descriptor instead.
func (*LoadCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_connector_proto_rawDescGZIP(), []int{5}
}

func (x *LoadCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadCheckpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LoadCheckpointResponse) GetCheckpoint() *Checkpoint {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

var File_api_gateway_v1_connector_proto protoreflect.FileDescriptor

const file_api_gateway_v1_connector_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/gateway/v1/connector.proto\x12\n" +
	"gateway.v1\x1a\x1bapi/gateway/v1/common.proto\"L\n" +
	"\x14BeginSnapshotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"table_name\x18\x02 \x01(\tR\ttableName\"k\n" +
	"\x0fStartCdcRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12A\n" +
	"\x10start_checkpoint\x18\x02 \x01(\v2\x16.gateway.v1.CheckpointR\x0fstartCheckpoint\"h\n" +
	"\x17CommitCheckpointRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x126\n" +
	"\n" +
	"checkpoint\x18\x02 \x01(\v2\x16.gateway.v1.CheckpointR\n" +
	"checkpoint\"4\n" +
	"\x18CommitCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x15LoadCheckpointRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x80\x01\n" +
	"\x16LoadCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x126\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\v2\x16.gateway.v1.CheckpointR\n" +
	"checkpoint2\xde\x02\n" +
	"\x10ConnectorService\x12N\n" +
	"\rBeginSnapshot\x12 .gateway.v1.BeginSnapshotRequest\x1a\x19.gateway.v1.SnapshotChunk0\x01\x12B\n" +
	"\bStartCdc\x12\x1b.gateway.v1.StartCdcRequest\x1a\x17.gateway.v1.ChangeEvent0\x01\x12]\n" +
	"\x10CommitCheckpoint\x12#.gateway.v1.CommitCheckpointRequest\x1a$.gateway.v1.CommitCheckpointResponse\x12W\n" +
	"\x0eLoadCheckpoint\x12!.gateway.v1.LoadCheckpointRequest\x1a\".gateway.v1.LoadCheckpointResponseB<Z:github.com/yogoosoft/elasticrelay/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_connector_proto_rawDescOnce sync.Once
	file_api_gateway_v1_connector_proto_rawDescData []byte
)

func file_api_gateway_v1_connector_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_connector_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_connector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_connector_proto_rawDesc), len(file_api_gateway_v1_connector_proto_rawDesc)))
	})
	return file_api_gateway_v1_connector_proto_rawDescData
}

var file_api_gateway_v1_connector_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_gateway_v1_connector_proto_goTypes = []any{
	(*BeginSnapshotRequest)(nil),     // 0: gateway.v1.BeginSnapshotRequest
	(*StartCdcRequest)(nil),          // 1: gateway.v1.StartCdcRequest
	(*CommitCheckpointRequest)(nil),  // 2: gateway.v1.CommitCheckpointRequest
	(*CommitCheckpointResponse)(nil), // 3: gateway.v1.CommitCheckpointResponse
	(*LoadCheckpointRequest)(nil),    // 4: gateway.v1.LoadCheckpointRequest
	(*LoadCheckpointResponse)(nil),   // 5: gateway.v1.LoadCheckpointResponse
	(*Checkpoint)(nil),               // 6: gateway.v1.Checkpoint
	(*SnapshotChunk)(nil),            // 7: gateway.v1.SnapshotChunk
	(*ChangeEvent)(nil),              // 8: gateway.v1.ChangeEvent
}
var file_api_gateway_v1_connector_proto_depIdxs = []int32{
	6, // 0: gateway.v1.StartCdcRequest.start_checkpoint:type_name -> gateway.v1.Checkpoint
	6, // 1: gateway.v1.CommitCheckpointRequest.checkpoint:type_name -> gateway.v1.Checkpoint
	6, // 2: gateway.v1.LoadCheckpointResponse.checkpoint:type_name -> gateway.v1.Checkpoint
	0, // 3: gateway.v1.ConnectorService.BeginSnapshot:input_type -> gateway.v1.BeginSnapshotRequest
	1, // 4: gateway.v1.ConnectorService.StartCdc:input_type -> gateway.v1.StartCdcRequest
	2, // 5: gateway.v1.ConnectorService.CommitCheckpoint:input_type -> gateway.v1.CommitCheckpointRequest
	4, // 6: gateway.v1.ConnectorService.LoadCheckpoint:input_type -> gateway.v1.LoadCheckpointRequest
	7, // 7: gateway.v1.ConnectorService.BeginSnapshot:output_type -> gateway.v1.SnapshotChunk
	8, // 8: gateway.v1.ConnectorService.StartCdc:output_type -> gateway.v1.ChangeEvent
	3, // 9: gateway.v1.ConnectorService.CommitCheckpoint:output_type -> gateway.v1.CommitCheckpointResponse
	5, // 10: gateway.v1.ConnectorService.LoadCheckpoint:output_type -> gateway.v1.LoadCheckpointResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_connector_proto_init() }
func file_api_gateway_v1_connector_proto_init() {
	if File_api_gateway_v1_connector_proto != nil {
		return
	}
	file_api_gateway_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_connector_proto_rawDesc), len(file_api_gateway_v1_connector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_connector_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_connector_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_connector_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_connector_proto = out.File
	file_api_gateway_v1_connector_proto_goTypes = nil
	file_api_gateway_v1_connector_proto_depIdxs = nil
}
