// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/gateway/v1/sink.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SinkService_BulkWrite_FullMethodName     = "/gateway.v1.SinkService/BulkWrite"
	SinkService_DescribeIndex_FullMethodName = "/gateway.v1.SinkService/DescribeIndex"
	SinkService_PutTemplate_FullMethodName   = "/gateway.v1.SinkService/PutTemplate"
	SinkService_SetupIlm_FullMethodName      = "/gateway.v1.SinkService/SetupIlm"
)

// SinkServiceClient is the client API for SinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SinkService is responsible for writing data to the destination (Elasticsearch).
type SinkServiceClient interface {
	// Writes a batch of change events to the sink.
	BulkWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChangeEvent, BulkWriteResponse], error)
	// Describes an Elasticsearch index.
	DescribeIndex(ctx context.Context, in *DescribeIndexRequest, opts ...grpc.CallOption) (*DescribeIndexResponse, error)
	// Creates or updates an Elasticsearch index template.
	PutTemplate(ctx context.Context, in *PutTemplateRequest, opts ...grpc.CallOption) (*PutTemplateResponse, error)
	// Sets up an Index Lifecycle Management (ILM) policy.
	SetupIlm(ctx context.Context, in *SetupIlmRequest, opts ...grpc.CallOption) (*SetupIlmResponse, error)
}

type sinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSinkServiceClient(cc grpc.ClientConnInterface) SinkServiceClient {
	return &sinkServiceClient{cc}
}

func (c *sinkServiceClient) BulkWrite(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ChangeEvent, BulkWriteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SinkService_ServiceDesc.Streams[0], SinkService_BulkWrite_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeEvent, BulkWriteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SinkService_BulkWriteClient = grpc.ClientStreamingClient[ChangeEvent, BulkWriteResponse]

func (c *sinkServiceClient) DescribeIndex(ctx context.Context, in *DescribeIndexRequest, opts ...grpc.CallOption) (*DescribeIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeIndexResponse)
	err := c.cc.Invoke(ctx, SinkService_DescribeIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkServiceClient) PutTemplate(ctx context.Context, in *PutTemplateRequest, opts ...grpc.CallOption) (*PutTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutTemplateResponse)
	err := c.cc.Invoke(ctx, SinkService_PutTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sinkServiceClient) SetupIlm(ctx context.Context, in *SetupIlmRequest, opts ...grpc.CallOption) (*SetupIlmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupIlmResponse)
	err := c.cc.Invoke(ctx, SinkService_SetupIlm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SinkServiceServer is the server API for SinkService service.
// All implementations must embed UnimplementedSinkServiceServer
// for forward compatibility.
//
// SinkService is responsible for writing data to the destination (Elasticsearch).
type SinkServiceServer interface {
	// Writes a batch of change events to the sink.
	BulkWrite(grpc.ClientStreamingServer[ChangeEvent, BulkWriteResponse]) error
	// Describes an Elasticsearch index.
	DescribeIndex(context.Context, *DescribeIndexRequest) (*DescribeIndexResponse, error)
	// Creates or updates an Elasticsearch index template.
	PutTemplate(context.Context, *PutTemplateRequest) (*PutTemplateResponse, error)
	// Sets up an Index Lifecycle Management (ILM) policy.
	SetupIlm(context.Context, *SetupIlmRequest) (*SetupIlmResponse, error)
	mustEmbedUnimplementedSinkServiceServer()
}

// UnimplementedSinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSinkServiceServer struct{}

func (UnimplementedSinkServiceServer) BulkWrite(grpc.ClientStreamingServer[ChangeEvent, BulkWriteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BulkWrite not implemented")
}
func (UnimplementedSinkServiceServer) DescribeIndex(context.Context, *DescribeIndexRequest) (*DescribeIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeIndex not implemented")
}
func (UnimplementedSinkServiceServer) PutTemplate(context.Context, *PutTemplateRequest) (*PutTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutTemplate not implemented")
}
func (UnimplementedSinkServiceServer) SetupIlm(context.Context, *SetupIlmRequest) (*SetupIlmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupIlm not implemented")
}
func (UnimplementedSinkServiceServer) mustEmbedUnimplementedSinkServiceServer() {}
func (UnimplementedSinkServiceServer) testEmbeddedByValue()                     {}

// UnsafeSinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SinkServiceServer will
// result in compilation errors.
type UnsafeSinkServiceServer interface {
	mustEmbedUnimplementedSinkServiceServer()
}

func RegisterSinkServiceServer(s grpc.ServiceRegistrar, srv SinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedSinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SinkService_ServiceDesc, srv)
}

func _SinkService_BulkWrite_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SinkServiceServer).BulkWrite(&grpc.GenericServerStream[ChangeEvent, BulkWriteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SinkService_BulkWriteServer = grpc.ClientStreamingServer[ChangeEvent, BulkWriteResponse]

func _SinkService_DescribeIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkServiceServer).DescribeIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkService_DescribeIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkServiceServer).DescribeIndex(ctx, req.(*DescribeIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkService_PutTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkServiceServer).PutTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkService_PutTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkServiceServer).PutTemplate(ctx, req.(*PutTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SinkService_SetupIlm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetupIlmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SinkServiceServer).SetupIlm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SinkService_SetupIlm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SinkServiceServer).SetupIlm(ctx, req.(*SetupIlmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SinkService_ServiceDesc is the grpc.ServiceDesc for SinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.SinkService",
	HandlerType: (*SinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DescribeIndex",
			Handler:    _SinkService_DescribeIndex_Handler,
		},
		{
			MethodName: "PutTemplate",
			Handler:    _SinkService_PutTemplate_Handler,
		},
		{
			MethodName: "SetupIlm",
			Handler:    _SinkService_SetupIlm_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkWrite",
			Handler:       _SinkService_BulkWrite_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/gateway/v1/sink.proto",
}
