// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/gateway/v1/sink.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BulkWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuccessCount  int32                  `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,3,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkWriteResponse) Reset() {
	*x = BulkWriteResponse{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkWriteResponse) ProtoMessage() {}

func (x *BulkWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkWriteResponse.ProtoReflect.Descriptor instead.
func (*BulkWriteResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{0}
}

func (x *BulkWriteResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BulkWriteResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BulkWriteResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type DescribeIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IndexName     string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeIndexRequest) Reset() {
	*x = DescribeIndexRequest{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeIndexRequest) ProtoMessage() {}

func (x *DescribeIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeIndexRequest.ProtoReflect.Descriptor instead.
func (*DescribeIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{1}
}

func (x *DescribeIndexRequest) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

type DescribeIndexResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IndexName       string                 `protobuf:"bytes,1,opt,name=index_name,json=indexName,proto3" json:"index_name,omitempty"`
	Exists          bool                   `protobuf:"varint,2,opt,name=exists,proto3" json:"exists,omitempty"`
	DocumentCount   int64                  `protobuf:"varint,3,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	IndexDefinition string                 `protobuf:"bytes,4,opt,name=index_definition,json=indexDefinition,proto3" json:"index_definition,omitempty"` // JSON string (optional)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DescribeIndexResponse) Reset() {
	*x = DescribeIndexResponse{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeIndexResponse) ProtoMessage() {}

func (x *DescribeIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeIndexResponse.ProtoReflect.Descriptor instead.
func (*DescribeIndexResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeIndexResponse) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *DescribeIndexResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *DescribeIndexResponse) GetDocumentCount() int64 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

func (x *DescribeIndexResponse) GetIndexDefinition() string {
	if x != nil {
		return x.IndexDefinition
	}
	return ""
}

type PutTemplateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemplateName       string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateDefinition string                 `protobuf:"bytes,2,opt,name=template_definition,json=templateDefinition,proto3" json:"template_definition,omitempty"` // JSON string
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PutTemplateRequest) Reset() {
	*x = PutTemplateRequest{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTemplateRequest) ProtoMessage() {}

func (x *PutTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTemplateRequest.ProtoReflect.Descriptor instead.
func (*PutTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{3}
}

func (x *PutTemplateRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *PutTemplateRequest) GetTemplateDefinition() string {
	if x != nil {
		return x.TemplateDefinition
	}
	return ""
}

type PutTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTemplateResponse) Reset() {
	*x = PutTemplateResponse{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTemplateResponse) ProtoMessage() {}

func (x *PutTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTemplateResponse.ProtoReflect.Descriptor instead.
func (*PutTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{4}
}

func (x *PutTemplateResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type SetupIlmRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PolicyName       string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyDefinition string                 `protobuf:"bytes,2,opt,name=policy_definition,json=policyDefinition,proto3" json:"policy_definition,omitempty"` // JSON string
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetupIlmRequest) Reset() {
	*x = SetupIlmRequest{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupIlmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupIlmRequest) ProtoMessage() {}

func (x *SetupIlmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupIlmRequest.ProtoReflect.Descriptor instead.
func (*SetupIlmRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{5}
}

func (x *SetupIlmRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *SetupIlmRequest) GetPolicyDefinition() string {
	if x != nil {
		return x.PolicyDefinition
	}
	return ""
}

type SetupIlmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupIlmResponse) Reset() {
	*x = SetupIlmResponse{}
	mi := &file_api_gateway_v1_sink_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupIlmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupIlmResponse) ProtoMessage() {}

func (x *SetupIlmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_sink_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupIlmResponse.ProtoReflect.Descriptor instead.
func (*SetupIlmResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_sink_proto_rawDescGZIP(), []int{6}
}

func (x *SetupIlmResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_api_gateway_v1_sink_proto protoreflect.FileDescriptor

const file_api_gateway_v1_sink_proto_rawDesc = "" +
	"\n" +
	"\x19api/gateway/v1/sink.proto\x12\n" +
	"gateway.v1\x1a\x1bapi/gateway/v1/common.proto\"z\n" +
	"\x11BulkWriteResponse\x12#\n" +
	"\rsuccess_count\x18\x01 \x01(\x05R\fsuccessCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x03 \x03(\tR\tfailedIds\"5\n" +
	"\x14DescribeIndexRequest\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\"\xa0\x01\n" +
	"\x15DescribeIndexResponse\x12\x1d\n" +
	"\n" +
	"index_name\x18\x01 \x01(\tR\tindexName\x12\x16\n" +
	"\x06exists\x18\x02 \x01(\bR\x06exists\x12%\n" +
	"\x0edocument_count\x18\x03 \x01(\x03R\rdocumentCount\x12)\n" +
	"\x10index_definition\x18\x04 \x01(\tR\x0findexDefinition\"j\n" +
	"\x12PutTemplateRequest\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12/\n" +
	"\x13template_definition\x18\x02 \x01(\tR\x12templateDefinition\"9\n" +
	"\x13PutTemplateResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"_\n" +
	"\x0fSetupIlmRequest\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12+\n" +
	"\x11policy_definition\x18\x02 \x01(\tR\x10policyDefinition\"6\n" +
	"\x10SetupIlmResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2\xc1\x02\n" +
	"\vSinkService\x12E\n" +
	"\tBulkWrite\x12\x17.gateway.v1.ChangeEvent\x1a\x1d.gateway.v1.BulkWriteResponse(\x01\x12T\n" +
	"\rDescribeIndex\x12 .gateway.v1.DescribeIndexRequest\x1a!.gateway.v1.DescribeIndexResponse\x12N\n" +
	"\vPutTemplate\x12\x1e.gateway.v1.PutTemplateRequest\x1a\x1f.gateway.v1.PutTemplateResponse\x12E\n" +
	"\bSetupIlm\x12\x1b.gateway.v1.SetupIlmRequest\x1a\x1c.gateway.v1.SetupIlmResponseB<Z:github.com/yogoosoft/elasticrelay/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_sink_proto_rawDescOnce sync.Once
	file_api_gateway_v1_sink_proto_rawDescData []byte
)

func file_api_gateway_v1_sink_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_sink_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_sink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_sink_proto_rawDesc), len(file_api_gateway_v1_sink_proto_rawDesc)))
	})
	return file_api_gateway_v1_sink_proto_rawDescData
}

var file_api_gateway_v1_sink_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_gateway_v1_sink_proto_goTypes = []any{
	(*BulkWriteResponse)(nil),     // 0: gateway.v1.BulkWriteResponse
	(*DescribeIndexRequest)(nil),  // 1: gateway.v1.DescribeIndexRequest
	(*DescribeIndexResponse)(nil), // 2: gateway.v1.DescribeIndexResponse
	(*PutTemplateRequest)(nil),    // 3: gateway.v1.PutTemplateRequest
	(*PutTemplateResponse)(nil),   // 4: gateway.v1.PutTemplateResponse
	(*SetupIlmRequest)(nil),       // 5: gateway.v1.SetupIlmRequest
	(*SetupIlmResponse)(nil),      // 6: gateway.v1.SetupIlmResponse
	(*ChangeEvent)(nil),           // 7: gateway.v1.ChangeEvent
}
var file_api_gateway_v1_sink_proto_depIdxs = []int32{
	7, // 0: gateway.v1.SinkService.BulkWrite:input_type -> gateway.v1.ChangeEvent
	1, // 1: gateway.v1.SinkService.DescribeIndex:input_type -> gateway.v1.DescribeIndexRequest
	3, // 2: gateway.v1.SinkService.PutTemplate:input_type -> gateway.v1.PutTemplateRequest
	5, // 3: gateway.v1.SinkService.SetupIlm:input_type -> gateway.v1.SetupIlmRequest
	0, // 4: gateway.v1.SinkService.BulkWrite:output_type -> gateway.v1.BulkWriteResponse
	2, // 5: gateway.v1.SinkService.DescribeIndex:output_type -> gateway.v1.DescribeIndexResponse
	4, // 6: gateway.v1.SinkService.PutTemplate:output_type -> gateway.v1.PutTemplateResponse
	6, // 7: gateway.v1.SinkService.SetupIlm:output_type -> gateway.v1.SetupIlmResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_sink_proto_init() }
func file_api_gateway_v1_sink_proto_init() {
	if File_api_gateway_v1_sink_proto != nil {
		return
	}
	file_api_gateway_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_sink_proto_rawDesc), len(file_api_gateway_v1_sink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_sink_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_sink_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_sink_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_sink_proto = out.File
	file_api_gateway_v1_sink_proto_goTypes = nil
	file_api_gateway_v1_sink_proto_depIdxs = nil
}
