// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: api/gateway/v1/transform.proto

package gatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransformService_ValidateRules_FullMethodName = "/gateway.v1.TransformService/ValidateRules"
	TransformService_ApplyRules_FullMethodName    = "/gateway.v1.TransformService/ApplyRules"
)

// TransformServiceClient is the client API for TransformService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransformService applies data governance and transformation rules.
type TransformServiceClient interface {
	// Validates a set of transformation rules.
	ValidateRules(ctx context.Context, in *ValidateRulesRequest, opts ...grpc.CallOption) (*ValidateRulesResponse, error)
	// Applies transformation rules to a stream of change events.
	ApplyRules(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeEvent, ChangeEvent], error)
}

type transformServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransformServiceClient(cc grpc.ClientConnInterface) TransformServiceClient {
	return &transformServiceClient{cc}
}

func (c *transformServiceClient) ValidateRules(ctx context.Context, in *ValidateRulesRequest, opts ...grpc.CallOption) (*ValidateRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRulesResponse)
	err := c.cc.Invoke(ctx, TransformService_ValidateRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transformServiceClient) ApplyRules(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChangeEvent, ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransformService_ServiceDesc.Streams[0], TransformService_ApplyRules_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChangeEvent, ChangeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransformService_ApplyRulesClient = grpc.BidiStreamingClient[ChangeEvent, ChangeEvent]

// TransformServiceServer is the server API for TransformService service.
// All implementations must embed UnimplementedTransformServiceServer
// for forward compatibility.
//
// TransformService applies data governance and transformation rules.
type TransformServiceServer interface {
	// Validates a set of transformation rules.
	ValidateRules(context.Context, *ValidateRulesRequest) (*ValidateRulesResponse, error)
	// Applies transformation rules to a stream of change events.
	ApplyRules(grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]) error
	mustEmbedUnimplementedTransformServiceServer()
}

// UnimplementedTransformServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransformServiceServer struct{}

func (UnimplementedTransformServiceServer) ValidateRules(context.Context, *ValidateRulesRequest) (*ValidateRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateRules not implemented")
}
func (UnimplementedTransformServiceServer) ApplyRules(grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]) error {
	return status.Errorf(codes.Unimplemented, "method ApplyRules not implemented")
}
func (UnimplementedTransformServiceServer) mustEmbedUnimplementedTransformServiceServer() {}
func (UnimplementedTransformServiceServer) testEmbeddedByValue()                          {}

// UnsafeTransformServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransformServiceServer will
// result in compilation errors.
type UnsafeTransformServiceServer interface {
	mustEmbedUnimplementedTransformServiceServer()
}

func RegisterTransformServiceServer(s grpc.ServiceRegistrar, srv TransformServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransformServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransformService_ServiceDesc, srv)
}

func _TransformService_ValidateRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransformServiceServer).ValidateRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransformService_ValidateRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransformServiceServer).ValidateRules(ctx, req.(*ValidateRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransformService_ApplyRules_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransformServiceServer).ApplyRules(&grpc.GenericServerStream[ChangeEvent, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransformService_ApplyRulesServer = grpc.BidiStreamingServer[ChangeEvent, ChangeEvent]

// TransformService_ServiceDesc is the grpc.ServiceDesc for TransformService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransformService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.TransformService",
	HandlerType: (*TransformServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateRules",
			Handler:    _TransformService_ValidateRules_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ApplyRules",
			Handler:       _TransformService_ApplyRules_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/gateway/v1/transform.proto",
}
