// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/gateway/v1/transform.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Definition    string                 `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"` // e.g., JSON or a custom DSL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformRule) Reset() {
	*x = TransformRule{}
	mi := &file_api_gateway_v1_transform_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformRule) ProtoMessage() {}

func (x *TransformRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_transform_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformRule.ProtoReflect.Descriptor instead.
func (*TransformRule) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_transform_proto_rawDescGZIP(), []int{0}
}

func (x *TransformRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TransformRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TransformRule) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

type ValidateRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*TransformRule       `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRulesRequest) Reset() {
	*x = ValidateRulesRequest{}
	mi := &file_api_gateway_v1_transform_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRulesRequest) ProtoMessage() {}

func (x *ValidateRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_transform_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRulesRequest.ProtoReflect.Descriptor instead.
func (*ValidateRulesRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_transform_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateRulesRequest) GetRules() []*TransformRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ValidateRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRulesResponse) Reset() {
	*x = ValidateRulesResponse{}
	mi := &file_api_gateway_v1_transform_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRulesResponse) ProtoMessage() {}

func (x *ValidateRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_transform_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRulesResponse.ProtoReflect.Descriptor instead.
func (*ValidateRulesResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_transform_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateRulesResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateRulesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_gateway_v1_transform_proto protoreflect.FileDescriptor

const file_api_gateway_v1_transform_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/gateway/v1/transform.proto\x12\n" +
	"gateway.v1\x1a\x1bapi/gateway/v1/common.proto\"S\n" +
	"\rTransformRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"definition\x18\x03 \x01(\tR\n" +
	"definition\"G\n" +
	"\x14ValidateRulesRequest\x12/\n" +
	"\x05rules\x18\x01 \x03(\v2\x19.gateway.v1.TransformRuleR\x05rules\"R\n" +
	"\x15ValidateRulesResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xac\x01\n" +
	"\x10TransformService\x12T\n" +
	"\rValidateRules\x12 .gateway.v1.ValidateRulesRequest\x1a!.gateway.v1.ValidateRulesResponse\x12B\n" +
	"\n" +
	"ApplyRules\x12\x17.gateway.v1.ChangeEvent\x1a\x17.gateway.v1.ChangeEvent(\x010\x01B<Z:github.com/yogoosoft/elasticrelay/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_transform_proto_rawDescOnce sync.Once
	file_api_gateway_v1_transform_proto_rawDescData []byte
)

func file_api_gateway_v1_transform_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_transform_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_transform_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_transform_proto_rawDesc), len(file_api_gateway_v1_transform_proto_rawDesc)))
	})
	return file_api_gateway_v1_transform_proto_rawDescData
}

var file_api_gateway_v1_transform_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_gateway_v1_transform_proto_goTypes = []any{
	(*TransformRule)(nil),         // 0: gateway.v1.TransformRule
	(*ValidateRulesRequest)(nil),  // 1: gateway.v1.ValidateRulesRequest
	(*ValidateRulesResponse)(nil), // 2: gateway.v1.ValidateRulesResponse
	(*ChangeEvent)(nil),           // 3: gateway.v1.ChangeEvent
}
var file_api_gateway_v1_transform_proto_depIdxs = []int32{
	0, // 0: gateway.v1.ValidateRulesRequest.rules:type_name -> gateway.v1.TransformRule
	1, // 1: gateway.v1.TransformService.ValidateRules:input_type -> gateway.v1.ValidateRulesRequest
	3, // 2: gateway.v1.TransformService.ApplyRules:input_type -> gateway.v1.ChangeEvent
	2, // 3: gateway.v1.TransformService.ValidateRules:output_type -> gateway.v1.ValidateRulesResponse
	3, // 4: gateway.v1.TransformService.ApplyRules:output_type -> gateway.v1.ChangeEvent
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_transform_proto_init() }
func file_api_gateway_v1_transform_proto_init() {
	if File_api_gateway_v1_transform_proto != nil {
		return
	}
	file_api_gateway_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_transform_proto_rawDesc), len(file_api_gateway_v1_transform_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_transform_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_transform_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_transform_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_transform_proto = out.File
	file_api_gateway_v1_transform_proto_goTypes = nil
	file_api_gateway_v1_transform_proto_depIdxs = nil
}
